-- Active: 1750388006843@@localhost@3306@falcon

CREATE DATABASE IF NOT EXISTS `falcon` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `falcon`;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `sample`;

CREATE TABLE `sample` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`name` VARCHAR(100) NOT NULL COMMENT '이름',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`)
);

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`username` VARCHAR(100) NOT NULL UNIQUE COMMENT '아이디',
	`password` VARCHAR(100) NOT NULL COMMENT '비밀번호',
	`name` VARCHAR(100) NOT NULL COMMENT '이름',
	`first_name` VARCHAR(100) NULL COMMENT '성',
	`last_name` VARCHAR(100) NULL COMMENT '이름',
	`tel` VARCHAR(100) NOT NULL COMMENT '전화번호',
	`email` VARCHAR(100) NOT NULL COMMENT '이메일',
	`enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '활성화여부',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	COMMENT '수정일자'
			,
	PRIMARY KEY (`no`)
);

DROP TABLE IF EXISTS `user_auth`;

CREATE TABLE `user_auth` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`user_no` BIGINT NOT NULL COMMENT 'FK',
	`username` VARCHAR(100) NOT NULL COMMENT '아이디',
	`auth` VARCHAR(100) NOT NULL COMMENT '권한',
	`name` VARCHAR(100) NOT NULL COMMENT '이름',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`),
	FOREIGN KEY (`user_no`) REFERENCES `users` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `shipments`;

CREATE TABLE `shipments` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL COMMENT 'UK',
	`user_no` BIGINT NOT NULL COMMENT 'FK',
	`tel` VARCHAR(100) NOT NULL COMMENT '전화번호',
	`recipient` VARCHAR(100) NOT NULL COMMENT '받는사람',
	`address` TEXT NOT NULL COMMENT '주소',
	`city` VARCHAR(100) NOT NULL COMMENT '도시',
	`postcode` VARCHAR(100) NOT NULL COMMENT '우편번호',
	`country` VARCHAR(100) NOT NULL COMMENT '국가/지역',
	`is_main` TINYINT(1) NULL DEFAULT 0 COMMENT '기본배송지여부',
	`delivery_request` TEXT NULL COMMENT '배송요청사항',
	`delivery_method` TEXT NULL COMMENT '수령방법',
	`tracking_no` VARCHAR(100) NULL,
	`ship_company` VARCHAR(100) NULL,
	`status` ENUM('배송준비중','배송시작','배송중','배송완료','주문취소') NULL DEFAULT '배송준비중' COMMENT '배송준비중, 배송시작, 배송중, 배송완료, 주문취소',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`),
	FOREIGN KEY (`user_no`) REFERENCES `users` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
);


DROP TABLE IF EXISTS `products`;

CREATE TABLE `products` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`name` VARCHAR(100) NOT NULL COMMENT '상품명',
	`stock` BIGINT NULL DEFAULT 0 COMMENT '상품재고',
	`category_no` BIGINT NOT NULL COMMENT 'FK (카테고리)',
	`category_large_no` BIGINT NOT NULL COMMENT 'FK (대분류)',
	`option_group_no` BIGINT NULL COMMENT 'FK (옵션그룹)',
	`price` DECIMAL(10,2) NOT NULL COMMENT '가격(기본가)',
	`ship_price` DECIMAL(10,2) NOT NULL COMMENT '배송비',
	`ship_msg` TEXT NULL COMMENT '배송안내',
	`summary` TEXT NULL COMMENT '상품요약정보',
	`content` TEXT NULL COMMENT '상품상세(HTML)',
	`is_new` TINYINT(1) NULL COMMENT '신상',
	`is_best` TINYINT(1) NULL COMMENT '베스트',
	`is_sold_out` TINYINT(1) NULL COMMENT '품절',
	`price_info` TEXT NULL COMMENT '가격설명',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`)
);

DROP TABLE IF EXISTS `popups`;

CREATE TABLE `popups` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`type` VARCHAR(100) NULL DEFAULT '메인' COMMENT '타입',
	`name` VARCHAR(100) NULL COMMENT '이름',
	`url` TEXT NULL COMMENT '이미지경로',
	`link` TEXT NULL COMMENT '링크',
	`seq` INT NULL DEFAULT 0 COMMENT '순서',
	`content` TEXT NULL COMMENT '내용',
	`started_at` TIMESTAMP NULL COMMENT '시작일',
	`ended_at` TIMESTAMP NULL COMMENT '종료일',
	`is_show` TINYiNT(1) NULL DEFAULT 1 COMMENT '공개여부',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`)
);



DROP TABLE IF EXISTS `payments`;

CREATE TABLE `payments` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`order_no` BIGINT NOT NULL COMMENT 'FK',
	`method` VARCHAR(100) NULL COMMENT '결제방식',
	`status` ENUM('결제대기','결제완료','결제실패','환불완료') NOT NULL DEFAULT '결제대기' COMMENT "상태 ( '결제대기','결제완료','결제실패','환불완료' )",
	`payment_key` VARCHAR(100) NOT NULL COMMENT '결제식별키',
	`amount` BIGINT NOT NULL COMMENT '결제금액',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`),
	FOREIGN KEY (`order_no`) REFERENCES `orders` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `options`;

CREATE TABLE `options` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`group_no` BIGINT NOT NULL COMMENT 'FK',
	`name` VARCHAR(100) NOT NULL COMMENT '옵션명',
	`price` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '옵션가격',
	`stock` BIGINT NOT NULL DEFAULT 0 COMMENT '옵션재고',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`),
	FOREIGN KEY (`group_no`) REFERENCES `option_group` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
); 

DROP TABLE IF EXISTS `address`;

CREATE TABLE `address` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`user_no` BIGINT NOT NULL COMMENT 'FK',
	`tel` VARCHAR(100) NOT NULL COMMENT '전화번호',
	`recipient` VARCHAR(100) NOT NULL COMMENT '받는사람',
	`address` TEXT NOT NULL COMMENT '주소',
	`city` VARCHAR(100) NOT NULL COMMENT '도시',
	`postcode` VARCHAR(100) NOT NULL COMMENT '우편번호',
	`country` VARCHAR(100) NOT NULL COMMENT '국가/지역',
	`is_main` TINYINT(1) NULL DEFAULT 0 COMMENT '기본배송지여부',
	`delivery_request` TEXT NULL COMMENT '배송요청사항',
	`delivery_method` TEXT NULL COMMENT '수령방법',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`),
	FOREIGN KEY (`user_no`) REFERENCES `users` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `carts`;

CREATE TABLE `carts` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`user_no` BIGINT NOT NULL COMMENT 'FK',
	`product_no` BIGINT NOT NULL COMMENT 'FK',
	`quantity` BIGINT NULL COMMENT '수량',
	`total_price` DECIMAL(10,2) NULL COMMENT '수량x가격',
	`options` TEXT NULL COMMENT '옵션들(JSON)',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`),
	FOREIGN KEY (`user_no`) REFERENCES `users` (`no`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (`product_no`) REFERENCES `products` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
);


DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `no` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `id` varchar(64) NOT NULL COMMENT 'UK',
  `user_no` bigint NOT NULL COMMENT 'FK',
  `address_no` bigint NULL COMMENT 'FK',
  `code` varchar(200) DEFAULT NULL COMMENT '주문코드 (20250101_상품번호_유저번호_당일시퀀스)',
  `title` text NOT NULL COMMENT '주문제목 (상품1 외 5건)',
  `guest_tel` varchar(100) DEFAULT NULL COMMENT '비회원 전화번호',
  `guest_email` varchar(100) DEFAULT NULL COMMENT '비회원 이메일',
  `guest_first_name` varchar(100) DEFAULT NULL COMMENT '비회원 성',
  `guest_last_name` varchar(100) DEFAULT NULL COMMENT '비회원 이름',
  `total_price` DECIMAL(10,2) DEFAULT NULL COMMENT '총 가격',
  `total_quantity` bigint DEFAULT NULL COMMENT '총 수량',
  `total_item_count` bigint DEFAULT NULL COMMENT '총 항목수',
  `ship_price` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '배송비',
  `payment_method` enum('CASH','COIN','CARD','TRANSFER') DEFAULT 'CARD' COMMENT '결제방식 (현금, 코인, 카드, 계좌이체)',
  `status` enum('결제대기','결제완료','배송중','배송완료','주문취소','환불완료') DEFAULT '결제대기' COMMENT '상태 (''결제대기'',''결제완료'',''배송중'',''배송완료'',''주문취소'',''환불완료'')',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
  PRIMARY KEY (`no`),
  UNIQUE KEY `id` (`id`),
  KEY `user_no` (`user_no`),
  KEY `address_no` (`address_no`),
  CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`user_no`) REFERENCES `users` (`no`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `orders_ibfk_2` FOREIGN KEY (`address_no`) REFERENCES `address` (`no`) ON DELETE SET NULL ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `order_item`;

CREATE TABLE `order_item` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`product_no` BIGINT NOT NULL COMMENT 'FK',
	`order_no` BIGINT NOT NULL COMMENT 'FK',
	`quantity` BIGINT NOT NULL DEFAULT 1 COMMENT '수량',
	`price` DECIMAL(10,2) NOT NULL COMMENT '가격',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`),
	FOREIGN KEY (`product_no`) REFERENCES `products` (`no`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (`order_no`) REFERENCES `orders` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `order_item_option`;

CREATE TABLE `order_item_option` (
	`no`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`order_item_no`	BIGINT	NOT NULL	COMMENT 'FK: 주문항목',
	`option_no`	BIGINT	NOT NULL	COMMENT 'FK: 선택한 옵션',
	`quantity`	BIGINT	NOT NULL	DEFAULT 1	COMMENT '해당 옵션 수량',
	`price`	DECIMAL(10,2)	NOT NULL	COMMENT '해당 옵션 가격 (snapshot)',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자',
	FOREIGN KEY (`order_item_no`) REFERENCES `order_item` (`no`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (`option_no`) REFERENCES `options` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
);



DROP TABLE IF EXISTS `media`;

CREATE TABLE `media` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`product_no` BIGINT NOT NULL COMMENT 'FK',
	`is_main` TINYiNT(1) NULL COMMENT '메인미디어',
	`is_thumb` TINYiNT(1) NULL COMMENT '썸네일',
	`thumb_seq` INT NULL COMMENT '썸네일순서',
	`type` ENUM('이미지','동영상','임베드') NULL COMMENT "타입 ('이미지','동영상','임베드')",
	`content` TEXT NULL COMMENT '컨텐츠( URL, img, video, iframe )',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`),
	FOREIGN KEY (`product_no`) REFERENCES `products` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `banners`;

CREATE TABLE `banners` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`type` VARCHAR(100) NULL DEFAULT '메인' COMMENT '타입',
	`name` VARCHAR(100) NULL COMMENT '이름',
	`main_title` TEXT NULL COMMENT '메인제목',
	`sub_title` TEXT NULL COMMENT '서브제목',
	`url` TEXT NULL COMMENT '이미지경로',
	`link` TEXT NULL COMMENT '링크',
	`seq` INT NULL DEFAULT 0 COMMENT '순서', 
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`)
);



DROP TABLE IF EXISTS `option_group`;

CREATE TABLE `option_group` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`name` VARCHAR(100) NOT NULL COMMENT '옵션그룹명',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`)
);


DROP TABLE IF EXISTS `cancellations`;
CREATE TABLE `cancellations` (
  `no` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `id` varchar(64) NOT NULL COMMENT 'UK',
  `order_no` bigint NOT NULL COMMENT 'FK',
  `type` enum('주문취소','반품') NOT NULL DEFAULT '주문취소' COMMENT '타입 (''주문취소'',''반품'')',
  `reason` text COMMENT '취소사유',
  `is_confirmed` tinyint(1) NOT NULL DEFAULT '0' COMMENT '승인여부',
  `is_refund` tinyint(1) DEFAULT '0' COMMENT '환불처리여부',
  `account_number` varchar(100) DEFAULT NULL COMMENT '환불계좌번호',
  `bank_name` varchar(100) DEFAULT NULL COMMENT '환불계좌은행',
  `depositor` varchar(100) DEFAULT NULL COMMENT '환불예금주',
  `status` ENUM('취소요청','취소완료','환불완료') NULL DEFAULT '취소요청' COMMENT '상태 (''취소요청'',''취소완료'',''환불완료'')',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
  PRIMARY KEY (`no`),
  UNIQUE KEY `id` (`id`),
  KEY `order_no` (`order_no`),
  CONSTRAINT `cancellations_ibfk_1` FOREIGN KEY (`order_no`) REFERENCES `orders` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
);


DROP TABLE IF EXISTS `category`;

CREATE TABLE `category` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`name` VARCHAR(100) NOT NULL COMMENT '카테고리명',
	`description` TEXT NULL COMMENT '카테고리설명',
	`seq` INT NOT NULL DEFAULT 0 COMMENT '순서',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`)
);



DROP TABLE IF EXISTS `category_large`;

CREATE TABLE `category_large` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL COMMENT 'UK',
	`category_no` BIGINT NOT NULL COMMENT 'FK',
	`name` VARCHAR(100) NOT NULL COMMENT '대분류',
	`seq` INT NOT NULL DEFAULT 0 COMMENT '순서',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`),
	FOREIGN KEY (`category_no`) REFERENCES `category` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
);


DROP TABLE IF EXISTS `code_groups`;

CREATE TABLE `code_groups` (
	`no`	BIGINT	NOT NULL AUTO_INCREMENT	COMMENT 'PK',
	`id`	VARCHAR(100)	NOT NULL	COMMENT 'UK',
	`name`	VARCHAR(100)	NOT NULL	COMMENT '코드그룸명',
	`description`	TEXT	NOT NULL	COMMENT '설명',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자',
	PRIMARY KEY (`no`)
);


DROP TABLE IF EXISTS `codes`;

CREATE TABLE `codes` (
	`no`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`id`	VARCHAR(100)	NOT NULL UNIQUE	COMMENT 'UK',
	`code_group_no`	BIGINT	NOT NULL	COMMENT 'FK',
	`name`	VARCHAR(100)	NOT NULL	COMMENT '코드명',
	`value`	VARCHAR(100)	NOT NULL	COMMENT '코드 값',
	`code`	VARCHAR(100)	NULL	COMMENT '업무코드',
	`description`	TEXT	NOT NULL	COMMENT '설명',
	`seq`	INT	NOT NULL	DEFAULT 0	COMMENT '순서',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자',
	FOREIGN KEY (`code_group_no`) REFERENCES `code_groups` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
);



DROP TABLE IF EXISTS `seq_groups`;

CREATE TABLE `seq_groups` (
	`no`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`id`	VARCHAR(100)	NOT NULL UNIQUE	COMMENT 'UK',
	`code`	VARCHAR(100)	NOT NULL	COMMENT '시퀀스를 식별하는 코드',
	`name`	VARCHAR(100)	NOT NULL	COMMENT '시퀀스 이름',
	`value`	BIGINT	NOT NULL	DEFAULT 0	COMMENT '그룹 누적 시퀀스 번호',
	`step`	BIGINT	NOT NULL	DEFAULT 1	COMMENT '증감치 (기본적으로 +1)',
	`description`	TEXT	NULL	COMMENT '설명',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
);


DROP TABLE IF EXISTS `seq`;

CREATE TABLE `seq` (
	`no`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`id`	VARCHAR(100)	NOT NULL UNIQUE	COMMENT 'UK',
	`seq_group_no`	BIGINT	NOT NULL	COMMENT 'FK',
	`code`	VARCHAR(100)	NOT NULL	COMMENT '시퀀스를 식별하는 코드 (seq_group_code)',
	`value`	BIGINT	NOT NULL	DEFAULT 0	COMMENT '현재 시퀀스 번호',
	`date`	DATE	NOT NULL	COMMENT '적용일자 (YYYY-MM-DD)',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자',
	FOREIGN KEY (`seq_group_no`) REFERENCES `seq_groups` (`no`) ON DELETE CASCADE ON UPDATE CASCADE
);




-- 이메일 발송 내역 테이블
DROP TABLE IF EXISTS `emails`;

CREATE TABLE `emails` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`template_no` BIGINT NULL COMMENT 'FK (이메일 템플릿)',
	`recipient_email` VARCHAR(255) NOT NULL COMMENT '받는사람 이메일',
	`recipient_name` VARCHAR(100) NULL COMMENT '받는사람 이름',
	`sender_email` VARCHAR(255) NOT NULL COMMENT '보내는사람 이메일',
	`sender_name` VARCHAR(100) NULL COMMENT '보내는사람 이름',
	`subject` VARCHAR(500) NOT NULL COMMENT '제목',
	`content` TEXT NOT NULL COMMENT '내용',
	`html_content` TEXT NULL COMMENT 'HTML 내용',
	`send_status` ENUM('PENDING','SENT','FAILED') NOT NULL DEFAULT 'PENDING' COMMENT '발송상태 (대기중, 발송완료, 발송실패)',
	`send_type` VARCHAR(50) NULL COMMENT '발송타입 (ORDER, PAYMENT, MANUAL 등)',
	`related_id` VARCHAR(64) NULL COMMENT '관련 ID (주문번호, 결제번호 등)',
	`send_at` TIMESTAMP NULL COMMENT '발송일시',
	`error_message` TEXT NULL COMMENT '오류메시지',
	`retry_count` INT NOT NULL DEFAULT 0 COMMENT '재시도 횟수',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`),
	INDEX `idx_recipient_email` (`recipient_email`),
	INDEX `idx_send_status` (`send_status`),
	INDEX `idx_send_type` (`send_type`),
	INDEX `idx_related_id` (`related_id`),
	INDEX `idx_send_at` (`send_at`)
);

-- 이메일 템플릿 테이블
DROP TABLE IF EXISTS `email_templates`;

CREATE TABLE `email_templates` (
	`no` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
	`id` VARCHAR(64) NOT NULL UNIQUE COMMENT 'UK',
	`name` VARCHAR(100) NOT NULL COMMENT '템플릿명',
	`type` VARCHAR(50) NOT NULL COMMENT '템플릿 타입 (ORDER, PAYMENT, MANUAL 등)',
	`subject` VARCHAR(500) NOT NULL COMMENT '제목 템플릿',
	`content` TEXT NOT NULL COMMENT '내용 템플릿',
	`is_html` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'HTML 여부',
	`html_content` TEXT NULL COMMENT 'HTML 내용 템플릿',
	`variables` TEXT NULL COMMENT '사용 가능한 변수 (JSON)',
	`is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '활성화 여부',
	`description` TEXT NULL COMMENT '설명',
	`created_by` VARCHAR(64) NULL COMMENT '등록자',
	`updated_by` VARCHAR(64) NULL COMMENT '수정자',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
	PRIMARY KEY (`no`),
	INDEX `idx_type` (`type`),
	INDEX `idx_is_active` (`is_active`)
);

-- 외래키 제약조건 추가
ALTER TABLE `emails` ADD CONSTRAINT `fk_emails_template` 
FOREIGN KEY (`template_no`) REFERENCES `email_templates` (`no`) ON DELETE SET NULL ON UPDATE CASCADE;



---------------------------------------

SET FOREIGN_KEY_CHECKS = 1;





